### ISSUE TITLE
[FR] Game list mode with centered names?

### ISSUE THREAD

**Issue by vanfanel** [anthonycaccese/art-book-next-batocera#6]
Hi there

I use this theme with JELOS extensively, but in order to avoid scrapping, etc, I would like to have the game list simply centered, without the space for the artwork/screenshots.
Would it be possible to add such visualization mode, please?

**Comment by anthonycaccese** [comment]
Yes, I am working on a refactor of the theme now that will have a basic view that is just the gamelist centered underneath the logo.  I'll post a link to a preview here soon.

**Comment by anthonycaccese** [comment]
you can try a preview of the next version here: https://github.com/anthonycaccese/art-book-next-jelos

to get to a list view open up theme customizations in the menu and change the gamelist view to "basic"

**Comment by vanfanel** [comment]
@anthonycaccese I tried the preview version and it's FANTASTIC!
Simply my dream theme now!

Can't wait to have it incorporated into JELOS distribution! Will that happen soon?

**Comment by anthonycaccese** [comment]
❤️ thank you!  Very glad to hear that its what you were looking for.

Yes it will be integrated into JELOS soon (likely in the next 2 weeks)

**Comment by anthonycaccese** [comment]
These changes are live now

**Comment by vanfanel** [comment]
Awesome!!! Thanks!! :D
