### ISSUE TITLE
Text Scroll Speed

### ISSUE THREAD

**Issue by wsamples01** [anthonycaccese/art-book-next-batocera#7]
Hello, I love the theme. 

One minor thing I think could be improved is that with scraped content, the text description of the game scrolls very slow. Same with if the name of a game is too long for the system to display (the left-to-right scroll). Could you point to where I could change the speeds of these in the code? 

Thank you.

**Comment by anthonycaccese** [comment]
Sorry I am not aware of a way to change the speed of scroll for those elements in batocera
